sudo: required
language: python
os: linux
python:
  - "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - sudo apt-get install -y portaudio19-dev
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest tests/ravestate/unittests.py --cov=./

after_success:
  - codecov
