sudo: required
language: python
os: linux
python:
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get install -y portaudio19-dev
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip3 install codecov pytest-cov
# command to run tests
script: pytest --cov=./
after_success:
  - codecov
