sudo: required
language: python
os: linux
python:
  - "3.5"
  - "3.6"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -y portaudio19-dev
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: pytest
